# Site settings
author: Christina Delavar
title: Living on Code Time
header-img: img/home-bg.png
email: c.delavar@gmail.com
copyright_name: Christina Delavar
description: > # this means to ignore newlines until "baseurl:"
  A Code of !Codswallop
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jinjo39

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
